# coding: utf-8

"""
    BV-BRC API

    API documentation for BV-BRC

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rpc_post_request import RpcPostRequest

class TestRpcPostRequest(unittest.TestCase):
    """RpcPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcPostRequest:
        """Test RpcPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcPostRequest`
        """
        model = RpcPostRequest()
        if include_optional:
            return RpcPostRequest(
                method = '',
                params = None
            )
        else:
            return RpcPostRequest(
        )
        """

    def testRpcPostRequest(self):
        """Test RpcPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
