# coding: utf-8

"""
    BV-BRC API

    API documentation for BV-BRC

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_accept_get(self) -> None:
        """Test case for accept_get

        Auto-generated summary for GET accept
        """
        pass

    def test_api_get(self) -> None:
        """Test case for api_get

        Auto-generated summary for GET /api
        """
        pass

    def test_collection_get(self) -> None:
        """Test case for collection_get

        Auto-generated summary for GET /:collection
        """
        pass

    def test_content_directory_get(self) -> None:
        """Test case for content_directory_get

        Auto-generated summary for GET contentDirectory
        """
        pass

    def test_content_id_get(self) -> None:
        """Test case for content_id_get

        Retrieve content by ID
        """
        pass

    def test_content_type_get(self) -> None:
        """Test case for content_type_get

        Auto-generated summary for GET content-type
        """
        pass

    def test_data_post(self) -> None:
        """Test case for data_post

        Add a new dataset entry
        """
        pass

    def test_data_type_get(self) -> None:
        """Test case for data_type_get

        Retrieve available data types
        """
        pass

    def test_distinct_collection_field_get(self) -> None:
        """Test case for distinct_collection_field_get

        Auto-generated summary for GET /distinct/:collection/:field
        """
        pass

    def test_distribute_url_get(self) -> None:
        """Test case for distribute_url_get

        Auto-generated summary for GET distributeURL
        """
        pass

    def test_doc_get(self) -> None:
        """Test case for doc_get

        Retrieve API documentation
        """
        pass

    def test_download_get(self) -> None:
        """Test case for download_get

        Download a file
        """
        pass

    def test_experiment_get(self) -> None:
        """Test case for experiment_get

        Auto-generated summary for GET /experiment
        """
        pass

    def test_experiment_id_get(self) -> None:
        """Test case for experiment_id_get

        Auto-generated summary for GET /experiment/:id
        """
        pass

    def test_experiment_id_id_list_id_list_get(self) -> None:
        """Test case for experiment_id_id_list_id_list_get

        Auto-generated summary for GET /experiment/:id/id-list/:id_list
        """
        pass

    def test_experiment_id_id_list_id_list_ids_get(self) -> None:
        """Test case for experiment_id_id_list_id_list_ids_get

        Auto-generated summary for GET /experiment/:id/id-list/:id_list/ids
        """
        pass

    def test_feature_type_get(self) -> None:
        """Test case for feature_type_get

        Auto-generated summary for GET feature_type
        """
        pass

    def test_genome2697049107626_track_list_get(self) -> None:
        """Test case for genome2697049107626_track_list_get

        Auto-generated summary for GET /genome/2697049.107626/trackList
        """
        pass

    def test_genome_id_features_seq_accession_get(self) -> None:
        """Test case for genome_id_features_seq_accession_get

        Auto-generated summary for GET /genome/:id/features/:seq_accession
        """
        pass

    def test_genome_id_names_get(self) -> None:
        """Test case for genome_id_names_get

        Auto-generated summary for GET /genome/:id/names/
        """
        pass

    def test_genome_id_refseqs_get(self) -> None:
        """Test case for genome_id_refseqs_get

        Auto-generated summary for GET /genome/:id/refseqs
        """
        pass

    def test_genome_id_stats_global_get(self) -> None:
        """Test case for genome_id_stats_global_get

        Auto-generated summary for GET /genome/:id/stats/global
        """
        pass

    def test_genome_id_stats_region_feature_densities_sequence_id_get(self) -> None:
        """Test case for genome_id_stats_region_feature_densities_sequence_id_get

        Auto-generated summary for GET /genome/:id/stats/regionFeatureDensities/:sequence_id
        """
        pass

    def test_genome_id_stats_region_sequence_id_get(self) -> None:
        """Test case for genome_id_stats_region_sequence_id_get

        Auto-generated summary for GET /genome/:id/stats/region/:sequence_id
        """
        pass

    def test_genome_id_track_list_get(self) -> None:
        """Test case for genome_id_track_list_get

        Auto-generated summary for GET /genome/:id/trackList
        """
        pass

    def test_genome_id_tracks_get(self) -> None:
        """Test case for genome_id_tracks_get

        Auto-generated summary for GET /genome/:id/tracks
        """
        pass

    def test_get(self) -> None:
        """Test case for get

        Auto-generated summary for GET *
        """
        pass

    def test_hpi_search_get(self) -> None:
        """Test case for hpi_search_get

        Search HPI data
        """
        pass

    def test_http_port_get(self) -> None:
        """Test case for http_port_get

        Auto-generated summary for GET http_port
        """
        pass

    def test_id_get(self) -> None:
        """Test case for id_get

        Auto-generated summary for GET /:id
        """
        pass

    def test_indexer_post(self) -> None:
        """Test case for indexer_post

        Trigger data indexing
        """
        pass

    def test_jbrowse_api_root_get(self) -> None:
        """Test case for jbrowse_api_root_get

        Auto-generated summary for GET jbrowseAPIRoot
        """
        pass

    def test_jbrowse_get(self) -> None:
        """Test case for jbrowse_get

        Retrieve JBrowse data
        """
        pass

    def test_permissions_genome_get(self) -> None:
        """Test case for permissions_genome_get

        Check genome permissions
        """
        pass

    def test_post(self) -> None:
        """Test case for post

        Auto-generated summary for POST *
        """
        pass

    def test_public_url_get(self) -> None:
        """Test case for public_url_get

        Auto-generated summary for GET publicURL
        """
        pass

    def test_query_multi_post(self) -> None:
        """Test case for query_multi_post

        Execute multiple queries
        """
        pass

    def test_queue_directory_get(self) -> None:
        """Test case for queue_directory_get

        Auto-generated summary for GET queueDirectory
        """
        pass

    def test_redis_get(self) -> None:
        """Test case for redis_get

        Auto-generated summary for GET redis
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Auto-generated summary for GET /
        """
        pass

    def test_root_post(self) -> None:
        """Test case for root_post

        Auto-generated summary for POST /
        """
        pass

    def test_rpc_post(self) -> None:
        """Test case for rpc_post

        Execute an RPC request
        """
        pass

    def test_solr_get(self) -> None:
        """Test case for solr_get

        Auto-generated summary for GET solr
        """
        pass

    def test_subsystem_summary_genome_id_get(self) -> None:
        """Test case for subsystem_summary_genome_id_get

        Auto-generated summary for GET /subsystem_summary/:genome_id
        """
        pass

    def test_summary_by_taxon_taxon_id_get(self) -> None:
        """Test case for summary_by_taxon_taxon_id_get

        Auto-generated summary for GET /summary_by_taxon/:taxon_id
        """
        pass

    def test_target_id_patch(self) -> None:
        """Test case for target_id_patch

        Auto-generated summary for PATCH /:target_id
        """
        pass

    def test_target_id_post(self) -> None:
        """Test case for target_id_post

        Auto-generated summary for POST /:target_id
        """
        pass

    def test_taxon_category_get(self) -> None:
        """Test case for taxon_category_get

        Auto-generated summary for GET /taxon_category/
        """
        pass

    def test_type_get(self) -> None:
        """Test case for type_get

        Auto-generated summary for GET type
        """
        pass

    def test_type_post(self) -> None:
        """Test case for type_post

        Auto-generated summary for POST /:type
        """
        pass


if __name__ == '__main__':
    unittest.main()
