/*
BV-BRC API

API documentation for BV-BRC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DataPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataPostRequest{}

// DataPostRequest struct for DataPostRequest
type DataPostRequest struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewDataPostRequest instantiates a new DataPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPostRequest() *DataPostRequest {
	this := DataPostRequest{}
	return &this
}

// NewDataPostRequestWithDefaults instantiates a new DataPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPostRequestWithDefaults() *DataPostRequest {
	this := DataPostRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DataPostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DataPostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DataPostRequest) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DataPostRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPostRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DataPostRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DataPostRequest) SetType(v string) {
	o.Type = &v
}

func (o DataPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableDataPostRequest struct {
	value *DataPostRequest
	isSet bool
}

func (v NullableDataPostRequest) Get() *DataPostRequest {
	return v.value
}

func (v *NullableDataPostRequest) Set(val *DataPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPostRequest(val *DataPostRequest) *NullableDataPostRequest {
	return &NullableDataPostRequest{value: val, isSet: true}
}

func (v NullableDataPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


