/*
BV-BRC API

API documentation for BV-BRC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QueryMultiPostRequestQueriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryMultiPostRequestQueriesInner{}

// QueryMultiPostRequestQueriesInner struct for QueryMultiPostRequestQueriesInner
type QueryMultiPostRequestQueriesInner struct {
	Query *string `json:"query,omitempty"`
	Filters map[string]interface{} `json:"filters,omitempty"`
}

// NewQueryMultiPostRequestQueriesInner instantiates a new QueryMultiPostRequestQueriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMultiPostRequestQueriesInner() *QueryMultiPostRequestQueriesInner {
	this := QueryMultiPostRequestQueriesInner{}
	return &this
}

// NewQueryMultiPostRequestQueriesInnerWithDefaults instantiates a new QueryMultiPostRequestQueriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMultiPostRequestQueriesInnerWithDefaults() *QueryMultiPostRequestQueriesInner {
	this := QueryMultiPostRequestQueriesInner{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *QueryMultiPostRequestQueriesInner) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMultiPostRequestQueriesInner) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *QueryMultiPostRequestQueriesInner) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *QueryMultiPostRequestQueriesInner) SetQuery(v string) {
	o.Query = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *QueryMultiPostRequestQueriesInner) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMultiPostRequestQueriesInner) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *QueryMultiPostRequestQueriesInner) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *QueryMultiPostRequestQueriesInner) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

func (o QueryMultiPostRequestQueriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMultiPostRequestQueriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	return toSerialize, nil
}

type NullableQueryMultiPostRequestQueriesInner struct {
	value *QueryMultiPostRequestQueriesInner
	isSet bool
}

func (v NullableQueryMultiPostRequestQueriesInner) Get() *QueryMultiPostRequestQueriesInner {
	return v.value
}

func (v *NullableQueryMultiPostRequestQueriesInner) Set(val *QueryMultiPostRequestQueriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMultiPostRequestQueriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMultiPostRequestQueriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMultiPostRequestQueriesInner(val *QueryMultiPostRequestQueriesInner) *NullableQueryMultiPostRequestQueriesInner {
	return &NullableQueryMultiPostRequestQueriesInner{value: val, isSet: true}
}

func (v NullableQueryMultiPostRequestQueriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMultiPostRequestQueriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


