/*
BV-BRC API

API documentation for BV-BRC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HpiSearchGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HpiSearchGet200Response{}

// HpiSearchGet200Response struct for HpiSearchGet200Response
type HpiSearchGet200Response struct {
	Results []HpiSearchGet200ResponseResultsInner `json:"results,omitempty"`
}

// NewHpiSearchGet200Response instantiates a new HpiSearchGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHpiSearchGet200Response() *HpiSearchGet200Response {
	this := HpiSearchGet200Response{}
	return &this
}

// NewHpiSearchGet200ResponseWithDefaults instantiates a new HpiSearchGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHpiSearchGet200ResponseWithDefaults() *HpiSearchGet200Response {
	this := HpiSearchGet200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *HpiSearchGet200Response) GetResults() []HpiSearchGet200ResponseResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []HpiSearchGet200ResponseResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HpiSearchGet200Response) GetResultsOk() ([]HpiSearchGet200ResponseResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *HpiSearchGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []HpiSearchGet200ResponseResultsInner and assigns it to the Results field.
func (o *HpiSearchGet200Response) SetResults(v []HpiSearchGet200ResponseResultsInner) {
	o.Results = v
}

func (o HpiSearchGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HpiSearchGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableHpiSearchGet200Response struct {
	value *HpiSearchGet200Response
	isSet bool
}

func (v NullableHpiSearchGet200Response) Get() *HpiSearchGet200Response {
	return v.value
}

func (v *NullableHpiSearchGet200Response) Set(val *HpiSearchGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHpiSearchGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHpiSearchGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHpiSearchGet200Response(val *HpiSearchGet200Response) *NullableHpiSearchGet200Response {
	return &NullableHpiSearchGet200Response{value: val, isSet: true}
}

func (v NullableHpiSearchGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHpiSearchGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


