/*
 * BV-BRC API
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HpiSearchGet200ResponseResultsInner
 */
public class HpiSearchGet200ResponseResultsInnerTest {
    private final HpiSearchGet200ResponseResultsInner model = new HpiSearchGet200ResponseResultsInner();

    /**
     * Model tests for HpiSearchGet200ResponseResultsInner
     */
    @Test
    public void testHpiSearchGet200ResponseResultsInner() {
        // TODO: test HpiSearchGet200ResponseResultsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
