/*
 * BV-BRC API
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.HpiSearchGet200ResponseResultsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HpiSearchGet200Response
 */
public class HpiSearchGet200ResponseTest {
    private final HpiSearchGet200Response model = new HpiSearchGet200Response();

    /**
     * Model tests for HpiSearchGet200Response
     */
    @Test
    public void testHpiSearchGet200Response() {
        // TODO: test HpiSearchGet200Response
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

}
