// <auto-generated>
/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// HpiSearchGet200Response
    /// </summary>
    public partial class HpiSearchGet200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HpiSearchGet200Response" /> class.
        /// </summary>
        /// <param name="results">results</param>
        [JsonConstructor]
        public HpiSearchGet200Response(Option<List<HpiSearchGet200ResponseResultsInner>?> results = default)
        {
            ResultsOption = results;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Results
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<HpiSearchGet200ResponseResultsInner>?> ResultsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [JsonPropertyName("results")]
        public List<HpiSearchGet200ResponseResultsInner>? Results { get { return this.ResultsOption; } set { this.ResultsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HpiSearchGet200Response {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HpiSearchGet200Response" />
    /// </summary>
    public class HpiSearchGet200ResponseJsonConverter : JsonConverter<HpiSearchGet200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="HpiSearchGet200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HpiSearchGet200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<HpiSearchGet200ResponseResultsInner>?> results = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "results":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                results = new Option<List<HpiSearchGet200ResponseResultsInner>?>(JsonSerializer.Deserialize<List<HpiSearchGet200ResponseResultsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class HpiSearchGet200Response.");

            return new HpiSearchGet200Response(results);
        }

        /// <summary>
        /// Serializes a <see cref="HpiSearchGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hpiSearchGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HpiSearchGet200Response hpiSearchGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, hpiSearchGet200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HpiSearchGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hpiSearchGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HpiSearchGet200Response hpiSearchGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (hpiSearchGet200Response.ResultsOption.IsSet && hpiSearchGet200Response.Results == null)
                throw new ArgumentNullException(nameof(hpiSearchGet200Response.Results), "Property is required for class HpiSearchGet200Response.");

            if (hpiSearchGet200Response.ResultsOption.IsSet)
            {
                writer.WritePropertyName("results");
                JsonSerializer.Serialize(writer, hpiSearchGet200Response.Results, jsonSerializerOptions);
            }
        }
    }
}
