// <auto-generated>
/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// QueryMultiPostRequest
    /// </summary>
    public partial class QueryMultiPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryMultiPostRequest" /> class.
        /// </summary>
        /// <param name="queries">queries</param>
        [JsonConstructor]
        public QueryMultiPostRequest(Option<List<QueryMultiPostRequestQueriesInner>?> queries = default)
        {
            QueriesOption = queries;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Queries
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<QueryMultiPostRequestQueriesInner>?> QueriesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Queries
        /// </summary>
        [JsonPropertyName("queries")]
        public List<QueryMultiPostRequestQueriesInner>? Queries { get { return this.QueriesOption; } set { this.QueriesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryMultiPostRequest {\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryMultiPostRequest" />
    /// </summary>
    public class QueryMultiPostRequestJsonConverter : JsonConverter<QueryMultiPostRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="QueryMultiPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryMultiPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<QueryMultiPostRequestQueriesInner>?> queries = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "queries":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                queries = new Option<List<QueryMultiPostRequestQueriesInner>?>(JsonSerializer.Deserialize<List<QueryMultiPostRequestQueriesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (queries.IsSet && queries.Value == null)
                throw new ArgumentNullException(nameof(queries), "Property is not nullable for class QueryMultiPostRequest.");

            return new QueryMultiPostRequest(queries);
        }

        /// <summary>
        /// Serializes a <see cref="QueryMultiPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryMultiPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryMultiPostRequest queryMultiPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryMultiPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryMultiPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryMultiPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryMultiPostRequest queryMultiPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryMultiPostRequest.QueriesOption.IsSet && queryMultiPostRequest.Queries == null)
                throw new ArgumentNullException(nameof(queryMultiPostRequest.Queries), "Property is required for class QueryMultiPostRequest.");

            if (queryMultiPostRequest.QueriesOption.IsSet)
            {
                writer.WritePropertyName("queries");
                JsonSerializer.Serialize(writer, queryMultiPostRequest.Queries, jsonSerializerOptions);
            }
        }
    }
}
