/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HpiSearchGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HpiSearchGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HpiSearchGet200Response
        //private HpiSearchGet200Response instance;

        public HpiSearchGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of HpiSearchGet200Response
            //instance = new HpiSearchGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HpiSearchGet200Response
        /// </summary>
        [Fact]
        public void HpiSearchGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HpiSearchGet200Response
            //Assert.IsType<HpiSearchGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
