/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HpiSearchGet200ResponseResultsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HpiSearchGet200ResponseResultsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HpiSearchGet200ResponseResultsInner
        //private HpiSearchGet200ResponseResultsInner instance;

        public HpiSearchGet200ResponseResultsInnerTests()
        {
            // TODO uncomment below to create an instance of HpiSearchGet200ResponseResultsInner
            //instance = new HpiSearchGet200ResponseResultsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HpiSearchGet200ResponseResultsInner
        /// </summary>
        [Fact]
        public void HpiSearchGet200ResponseResultsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" HpiSearchGet200ResponseResultsInner
            //Assert.IsType<HpiSearchGet200ResponseResultsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
