/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing QueryMultiPostRequestQueriesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryMultiPostRequestQueriesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryMultiPostRequestQueriesInner
        //private QueryMultiPostRequestQueriesInner instance;

        public QueryMultiPostRequestQueriesInnerTests()
        {
            // TODO uncomment below to create an instance of QueryMultiPostRequestQueriesInner
            //instance = new QueryMultiPostRequestQueriesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryMultiPostRequestQueriesInner
        /// </summary>
        [Fact]
        public void QueryMultiPostRequestQueriesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryMultiPostRequestQueriesInner
            //Assert.IsType<QueryMultiPostRequestQueriesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
    }
}
