/*
 * BV-BRC API
 *
 * API documentation for BV-BRC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RpcPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RpcPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RpcPostRequest
        //private RpcPostRequest instance;

        public RpcPostRequestTests()
        {
            // TODO uncomment below to create an instance of RpcPostRequest
            //instance = new RpcPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RpcPostRequest
        /// </summary>
        [Fact]
        public void RpcPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RpcPostRequest
            //Assert.IsType<RpcPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
    }
}
